$(document).ready(function(){
    $("#one").click(function(){
        $(".design").show();
    })
})
$(document).ready(function(){
    $(".design").click(function(){
        $(".design").hide();
    })
})
$(document).ready(function(){
    $("#two").click(function(){
        $(".development").show();
    })
})
$(document).ready(function(){
    $(".development").click(function(){
        $(".development").hide();
    })
})
$(document).ready(function(){
    $("#three").click(function(){
        $(".product").show();
    })
})
$(document).ready(function(){
    $(".product").click(function(){
        $(".product").hide();
    })
})
